// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzfhddwanwkqayszygaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16ZmhkZHdhbndrcWF5c3p5Z2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDc0ODYsImV4cCI6MjA2MzMyMzQ4Nn0.rZ8qTnFu4TzwXSE_NnRGcU5700L2wf53kayEbR5AtxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);